<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_logo</name>
   <tag></tag>
   <elementGuidId>77339605-2a19-4c29-8ab3-67287ea3dfc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' logo ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a034a660-261f-4a04-9cba-d1ebeaa49b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ft.umj.ac.id/ftumj/img-front/demos/construction/7521.png</value>
      <webElementGuid>cdc3ea43-5426-48bf-aceb-8443b8b4cf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>8f108838-11d8-4b1f-8b71-c599043a4de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d082c376eaadf62e30b453eeef86205b</value>
      <webElementGuid>d3004663-f72f-4995-9cce-df3f29381c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' logo ')]</value>
      <webElementGuid>629e673a-19f1-4e8e-9a54-83d832b15b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' logo ')]</value>
      <webElementGuid>cd043533-0541-4bba-a254-caefbf617df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ft.umj.ac.id/ftumj/img-front/demos/construction/7521.png']</value>
      <webElementGuid>623f4bbf-1e16-425c-ac6b-6d646f3c37ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
